//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceParametros {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceParametros.IServiceParametros")]
    public interface IServiceParametros {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceParametros/TelefonosObligatorios", ReplyAction="http://tempuri.org/IServiceParametros/TelefonosObligatoriosResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Parametros.ParametrosTelefonos> TelefonosObligatorios(int idTipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceParametros/ObtenerTelefonosParametrosIdTipoUsuario", ReplyAction="http://tempuri.org/IServiceParametros/ObtenerTelefonosParametrosIdTipoUsuarioResp" +
            "onse")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.TelefonoUsuario> ObtenerTelefonosParametrosIdTipoUsuario(int idTipoUsuario, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceParametros/ObtenerCorreosParametrosIdTipoUsuario", ReplyAction="http://tempuri.org/IServiceParametros/ObtenerCorreosParametrosIdTipoUsuarioRespon" +
            "se")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.CorreoUsuario> ObtenerCorreosParametrosIdTipoUsuario(int idTipoUsuario, bool insertarSeleccion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceParametrosChannel : KiiniHelp.ServiceParametros.IServiceParametros, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceParametrosClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceParametros.IServiceParametros>, KiiniHelp.ServiceParametros.IServiceParametros {
        
        public ServiceParametrosClient() {
        }
        
        public ServiceParametrosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceParametrosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceParametrosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceParametrosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Parametros.ParametrosTelefonos> TelefonosObligatorios(int idTipoUsuario) {
            return base.Channel.TelefonosObligatorios(idTipoUsuario);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.TelefonoUsuario> ObtenerTelefonosParametrosIdTipoUsuario(int idTipoUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerTelefonosParametrosIdTipoUsuario(idTipoUsuario, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.Usuarios.CorreoUsuario> ObtenerCorreosParametrosIdTipoUsuario(int idTipoUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerCorreosParametrosIdTipoUsuario(idTipoUsuario, insertarSeleccion);
        }
    }
}
