//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceCatalogosSistema {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCatalogosSistema.IServiceCatalogosSistema")]
    public interface IServiceCatalogosSistema {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposUsuario", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposUsuarioResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoUsuario> ObtenerTiposUsuario(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposTelefono", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposTelefonoResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoTelefono> ObtenerTiposTelefono(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/ObtenerColoniasCp", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/ObtenerColoniasCpResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.Domicilio.Colonia> ObtenerColoniasCp(int cp, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/ObtenerRoles", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/ObtenerRolesResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Rol> ObtenerRoles(int idTipoUsuario, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposGruposByRol", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposGruposByRolResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoGrupo> ObtenerTiposGruposByRol(int idrol, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposGrupo", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposGrupoResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoGrupo> ObtenerTiposGrupo(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/ObtenerTipoCampoMascara", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/ObtenerTipoCampoMascaraResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Mascaras.TipoCampoMascara> ObtenerTipoCampoMascara(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/TipoCampoMascaraId", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/TipoCampoMascaraIdResponse")]
        KiiniNet.Entities.Cat.Mascaras.TipoCampoMascara TipoCampoMascaraId(int idTipoCampo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/ObtenerCatalogosMascaraCaptura", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/ObtenerCatalogosMascaraCapturaRespons" +
            "e")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Catalogos> ObtenerCatalogosMascaraCaptura(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposArbolAcceso", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposArbolAccesoResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoArbolAcceso> ObtenerTiposArbolAcceso(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/ObtenerTipoInformacionConsulta", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/ObtenerTipoInformacionConsultaRespons" +
            "e")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoInfConsulta> ObtenerTipoInformacionConsulta(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/ObtenerTipoDocumentos", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/ObtenerTipoDocumentosResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoDocumento> ObtenerTipoDocumentos(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposDocumentoId", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposDocumentoIdResponse")]
        KiiniNet.Entities.Cat.Sistema.TipoDocumento ObtenerTiposDocumentoId(int idTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposEncuesta", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/ObtenerTiposEncuestaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoEncuesta> ObtenerTiposEncuesta(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosSistema/TipoEncuestaId", ReplyAction="http://tempuri.org/IServiceCatalogosSistema/TipoEncuestaIdResponse")]
        KiiniNet.Entities.Cat.Sistema.TipoEncuesta TipoEncuestaId(int idTipoEncuesta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCatalogosSistemaChannel : KiiniHelp.ServiceCatalogosSistema.IServiceCatalogosSistema, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCatalogosSistemaClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceCatalogosSistema.IServiceCatalogosSistema>, KiiniHelp.ServiceCatalogosSistema.IServiceCatalogosSistema {
        
        public ServiceCatalogosSistemaClient() {
        }
        
        public ServiceCatalogosSistemaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCatalogosSistemaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogosSistemaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogosSistemaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoUsuario> ObtenerTiposUsuario(bool insertarSeleccion) {
            return base.Channel.ObtenerTiposUsuario(insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoTelefono> ObtenerTiposTelefono(bool insertarSeleccion) {
            return base.Channel.ObtenerTiposTelefono(insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.Domicilio.Colonia> ObtenerColoniasCp(int cp, bool insertarSeleccion) {
            return base.Channel.ObtenerColoniasCp(cp, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Rol> ObtenerRoles(int idTipoUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerRoles(idTipoUsuario, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoGrupo> ObtenerTiposGruposByRol(int idrol, bool insertarSeleccion) {
            return base.Channel.ObtenerTiposGruposByRol(idrol, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoGrupo> ObtenerTiposGrupo(bool insertarSeleccion) {
            return base.Channel.ObtenerTiposGrupo(insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Mascaras.TipoCampoMascara> ObtenerTipoCampoMascara(bool insertarSeleccion) {
            return base.Channel.ObtenerTipoCampoMascara(insertarSeleccion);
        }
        
        public KiiniNet.Entities.Cat.Mascaras.TipoCampoMascara TipoCampoMascaraId(int idTipoCampo) {
            return base.Channel.TipoCampoMascaraId(idTipoCampo);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.Catalogos> ObtenerCatalogosMascaraCaptura(bool insertarSeleccion) {
            return base.Channel.ObtenerCatalogosMascaraCaptura(insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoArbolAcceso> ObtenerTiposArbolAcceso(bool insertarSeleccion) {
            return base.Channel.ObtenerTiposArbolAcceso(insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoInfConsulta> ObtenerTipoInformacionConsulta(bool insertarSeleccion) {
            return base.Channel.ObtenerTipoInformacionConsulta(insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoDocumento> ObtenerTipoDocumentos(bool insertarSeleccion) {
            return base.Channel.ObtenerTipoDocumentos(insertarSeleccion);
        }
        
        public KiiniNet.Entities.Cat.Sistema.TipoDocumento ObtenerTiposDocumentoId(int idTipoDocumento) {
            return base.Channel.ObtenerTiposDocumentoId(idTipoDocumento);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoEncuesta> ObtenerTiposEncuesta(bool insertarSeleccion) {
            return base.Channel.ObtenerTiposEncuesta(insertarSeleccion);
        }
        
        public KiiniNet.Entities.Cat.Sistema.TipoEncuesta TipoEncuestaId(int idTipoEncuesta) {
            return base.Channel.TipoEncuestaId(idTipoEncuesta);
        }
    }
}
