//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiiniHelp.ServiceCatalogosUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCatalogosUsuario.IServiceCatalogosUsuario")]
    public interface IServiceCatalogosUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerTipoSubGrupos", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerTipoSubGruposResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoSubGrupo> ObtenerTipoSubGrupos(int idTipoGrupo, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerGruposUsuario", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerGruposUsuarioResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.GrupoUsuario> ObtenerGruposUsuario(int idTipoGrupo, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSubGruposUsuario", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSubGruposUsuarioResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperSubGurpoUsuario> ObtenerSubGruposUsuario(int idGrupoUsuario, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerPais", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerPaisResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.Pais> ObtenerPais(int idTipoUsuario, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerCampus", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerCampusResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.Campus> ObtenerCampus(int idTipoUsuario, int idPais, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerTorres", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerTorresResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.Torre> ObtenerTorres(int idTipoUsuario, int idCampus, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerPisos", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerPisosResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.Piso> ObtenerPisos(int idTipoUsuario, int idTorre, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerZonas", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerZonasResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.Zona> ObtenerZonas(int idTipoUsuario, int idPiso, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSubZonas", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSubZonasResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.SubZona> ObtenerSubZonas(int idTipoUsuario, int idZona, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSiteRacks", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSiteRacksResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.SiteRack> ObtenerSiteRacks(int idTipoUsuario, int idSubZona, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerHoldings", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerHoldingsResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.Holding> ObtenerHoldings(int idTipoUsuario, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerCompañias", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerCompañiasResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.Compania> ObtenerCompañias(int idTipoUsuario, int idHolding, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerDirecciones", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerDireccionesResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.Direccion> ObtenerDirecciones(int idTipoUsuario, int idCompañia, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSubDirecciones", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSubDireccionesResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.SubDireccion> ObtenerSubDirecciones(int idTipoUsuario, int idDireccoin, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerGerencias", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerGerenciasResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.Gerencia> ObtenerGerencias(int idTipoUsuario, int idSubdireccion, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSubGerencias", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSubGerenciasResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.SubGerencia> ObtenerSubGerencias(int idTipoUsuario, int idGerencia, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerJefaturas", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerJefaturasResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.Jefatura> ObtenerJefaturas(int idTipoUsuario, int idSubGerencia, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarUbicacion", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarUbicacionResponse")]
        void GuardarUbicacion(KiiniNet.Entities.Cat.Operacion.Ubicacion ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarOrganizacion", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarOrganizacionResponse")]
        void GuardarOrganizacion(KiiniNet.Entities.Cat.Operacion.Organizacion organizacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarHolding", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarHoldingResponse")]
        void GuardarHolding(KiiniNet.Entities.Cat.Arbol.Organizacion.Holding entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarCompania", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarCompaniaResponse")]
        void GuardarCompania(KiiniNet.Entities.Cat.Arbol.Organizacion.Compania entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarDireccion", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarDireccionResponse")]
        void GuardarDireccion(KiiniNet.Entities.Cat.Arbol.Organizacion.Direccion entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarSubDireccion", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarSubDireccionResponse")]
        void GuardarSubDireccion(KiiniNet.Entities.Cat.Arbol.Organizacion.SubDireccion entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarGerencia", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarGerenciaResponse")]
        void GuardarGerencia(KiiniNet.Entities.Cat.Arbol.Organizacion.Gerencia entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarSubGerencia", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarSubGerenciaResponse")]
        void GuardarSubGerencia(KiiniNet.Entities.Cat.Arbol.Organizacion.SubGerencia entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarJefatura", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarJefaturaResponse")]
        void GuardarJefatura(KiiniNet.Entities.Cat.Arbol.Organizacion.Jefatura entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarGrupoUsuario", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarGrupoUsuarioResponse")]
        void GuardarGrupoUsuario(KiiniNet.Entities.Cat.Usuario.GrupoUsuario grupoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerGrupoUsuarioById", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerGrupoUsuarioByIdResponse")]
        KiiniNet.Entities.Cat.Usuario.GrupoUsuario ObtenerGrupoUsuarioById(int idGrupoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSubGrupoUsuario", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSubGrupoUsuarioResponse")]
        KiiniNet.Entities.Cat.Usuario.SubGrupoUsuario ObtenerSubGrupoUsuario(int idGrupoUsuario, int idTipoSubGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel1", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel1Response")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel1> ObtenerNivel1(int idTipoArbol, int idTipoUsuario, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel2", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel2Response")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel2> ObtenerNivel2(int idTipoArbol, int idTipoUsuario, int idNivel1, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel3", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel3Response")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel3> ObtenerNivel3(int idTipoArbol, int idTipoUsuario, int idNivel2, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel4", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel4Response")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel4> ObtenerNivel4(int idTipoArbol, int idTipoUsuario, int idNivel3, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel5", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel5Response")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel5> ObtenerNivel5(int idTipoArbol, int idTipoUsuario, int idNivel4, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel6", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel6Response")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel6> ObtenerNivel6(int idTipoArbol, int idTipoUsuario, int idNivel5, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel7", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerNivel7Response")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel7> ObtenerNivel7(int idTipoArbol, int idTipoUsuario, int idNivel6, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/EsNodoTerminal", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/EsNodoTerminalResponse")]
        bool EsNodoTerminal(int idTipoUsuario, int idTipoArbol, int nivel1, System.Nullable<int> nivel2, System.Nullable<int> nivel3, System.Nullable<int> nivel4, System.Nullable<int> nivel5, System.Nullable<int> nivel6, System.Nullable<int> nivel7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarArbol", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarArbolResponse")]
        void GuardarArbol(KiiniNet.Entities.Cat.Operacion.ArbolAcceso arbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerInformacionConsulta", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerInformacionConsultaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Operacion.InformacionConsulta> ObtenerInformacionConsulta(KinniNet.Business.Utils.BusinessVariables.EnumTiposInformacionConsulta tipoinfoConsulta, bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarInformacionConsulta", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarInformacionConsultaResponse")]
        void GuardarInformacionConsulta(KiiniNet.Entities.Operacion.InformacionConsulta informacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSla", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerSlaResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.SLA> ObtenerSla(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarSla", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarSlaResponse")]
        void GuardarSla(KiiniNet.Entities.Cat.Usuario.SLA sla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/ObtenerEncuestas", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/ObtenerEncuestasResponse")]
        System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Encuesta> ObtenerEncuestas(bool insertarSeleccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogosUsuario/GuardarEncuesta", ReplyAction="http://tempuri.org/IServiceCatalogosUsuario/GuardarEncuestaResponse")]
        void GuardarEncuesta(KiiniNet.Entities.Cat.Usuario.Encuesta encuesta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCatalogosUsuarioChannel : KiiniHelp.ServiceCatalogosUsuario.IServiceCatalogosUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCatalogosUsuarioClient : System.ServiceModel.ClientBase<KiiniHelp.ServiceCatalogosUsuario.IServiceCatalogosUsuario>, KiiniHelp.ServiceCatalogosUsuario.IServiceCatalogosUsuario {
        
        public ServiceCatalogosUsuarioClient() {
        }
        
        public ServiceCatalogosUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCatalogosUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogosUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogosUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Sistema.TipoSubGrupo> ObtenerTipoSubGrupos(int idTipoGrupo, bool insertarSeleccion) {
            return base.Channel.ObtenerTipoSubGrupos(idTipoGrupo, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.GrupoUsuario> ObtenerGruposUsuario(int idTipoGrupo, bool insertarSeleccion) {
            return base.Channel.ObtenerGruposUsuario(idTipoGrupo, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Helper.HelperSubGurpoUsuario> ObtenerSubGruposUsuario(int idGrupoUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerSubGruposUsuario(idGrupoUsuario, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.Pais> ObtenerPais(int idTipoUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerPais(idTipoUsuario, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.Campus> ObtenerCampus(int idTipoUsuario, int idPais, bool insertarSeleccion) {
            return base.Channel.ObtenerCampus(idTipoUsuario, idPais, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.Torre> ObtenerTorres(int idTipoUsuario, int idCampus, bool insertarSeleccion) {
            return base.Channel.ObtenerTorres(idTipoUsuario, idCampus, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.Piso> ObtenerPisos(int idTipoUsuario, int idTorre, bool insertarSeleccion) {
            return base.Channel.ObtenerPisos(idTipoUsuario, idTorre, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.Zona> ObtenerZonas(int idTipoUsuario, int idPiso, bool insertarSeleccion) {
            return base.Channel.ObtenerZonas(idTipoUsuario, idPiso, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.SubZona> ObtenerSubZonas(int idTipoUsuario, int idZona, bool insertarSeleccion) {
            return base.Channel.ObtenerSubZonas(idTipoUsuario, idZona, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Ubicaciones.SiteRack> ObtenerSiteRacks(int idTipoUsuario, int idSubZona, bool insertarSeleccion) {
            return base.Channel.ObtenerSiteRacks(idTipoUsuario, idSubZona, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.Holding> ObtenerHoldings(int idTipoUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerHoldings(idTipoUsuario, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.Compania> ObtenerCompañias(int idTipoUsuario, int idHolding, bool insertarSeleccion) {
            return base.Channel.ObtenerCompañias(idTipoUsuario, idHolding, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.Direccion> ObtenerDirecciones(int idTipoUsuario, int idCompañia, bool insertarSeleccion) {
            return base.Channel.ObtenerDirecciones(idTipoUsuario, idCompañia, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.SubDireccion> ObtenerSubDirecciones(int idTipoUsuario, int idDireccoin, bool insertarSeleccion) {
            return base.Channel.ObtenerSubDirecciones(idTipoUsuario, idDireccoin, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.Gerencia> ObtenerGerencias(int idTipoUsuario, int idSubdireccion, bool insertarSeleccion) {
            return base.Channel.ObtenerGerencias(idTipoUsuario, idSubdireccion, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.SubGerencia> ObtenerSubGerencias(int idTipoUsuario, int idGerencia, bool insertarSeleccion) {
            return base.Channel.ObtenerSubGerencias(idTipoUsuario, idGerencia, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Organizacion.Jefatura> ObtenerJefaturas(int idTipoUsuario, int idSubGerencia, bool insertarSeleccion) {
            return base.Channel.ObtenerJefaturas(idTipoUsuario, idSubGerencia, insertarSeleccion);
        }
        
        public void GuardarUbicacion(KiiniNet.Entities.Cat.Operacion.Ubicacion ubicacion) {
            base.Channel.GuardarUbicacion(ubicacion);
        }
        
        public void GuardarOrganizacion(KiiniNet.Entities.Cat.Operacion.Organizacion organizacion) {
            base.Channel.GuardarOrganizacion(organizacion);
        }
        
        public void GuardarHolding(KiiniNet.Entities.Cat.Arbol.Organizacion.Holding entidad) {
            base.Channel.GuardarHolding(entidad);
        }
        
        public void GuardarCompania(KiiniNet.Entities.Cat.Arbol.Organizacion.Compania entidad) {
            base.Channel.GuardarCompania(entidad);
        }
        
        public void GuardarDireccion(KiiniNet.Entities.Cat.Arbol.Organizacion.Direccion entidad) {
            base.Channel.GuardarDireccion(entidad);
        }
        
        public void GuardarSubDireccion(KiiniNet.Entities.Cat.Arbol.Organizacion.SubDireccion entidad) {
            base.Channel.GuardarSubDireccion(entidad);
        }
        
        public void GuardarGerencia(KiiniNet.Entities.Cat.Arbol.Organizacion.Gerencia entidad) {
            base.Channel.GuardarGerencia(entidad);
        }
        
        public void GuardarSubGerencia(KiiniNet.Entities.Cat.Arbol.Organizacion.SubGerencia entidad) {
            base.Channel.GuardarSubGerencia(entidad);
        }
        
        public void GuardarJefatura(KiiniNet.Entities.Cat.Arbol.Organizacion.Jefatura entidad) {
            base.Channel.GuardarJefatura(entidad);
        }
        
        public void GuardarGrupoUsuario(KiiniNet.Entities.Cat.Usuario.GrupoUsuario grupoUsuario) {
            base.Channel.GuardarGrupoUsuario(grupoUsuario);
        }
        
        public KiiniNet.Entities.Cat.Usuario.GrupoUsuario ObtenerGrupoUsuarioById(int idGrupoUsuario) {
            return base.Channel.ObtenerGrupoUsuarioById(idGrupoUsuario);
        }
        
        public KiiniNet.Entities.Cat.Usuario.SubGrupoUsuario ObtenerSubGrupoUsuario(int idGrupoUsuario, int idTipoSubGrupo) {
            return base.Channel.ObtenerSubGrupoUsuario(idGrupoUsuario, idTipoSubGrupo);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel1> ObtenerNivel1(int idTipoArbol, int idTipoUsuario, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel1(idTipoArbol, idTipoUsuario, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel2> ObtenerNivel2(int idTipoArbol, int idTipoUsuario, int idNivel1, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel2(idTipoArbol, idTipoUsuario, idNivel1, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel3> ObtenerNivel3(int idTipoArbol, int idTipoUsuario, int idNivel2, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel3(idTipoArbol, idTipoUsuario, idNivel2, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel4> ObtenerNivel4(int idTipoArbol, int idTipoUsuario, int idNivel3, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel4(idTipoArbol, idTipoUsuario, idNivel3, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel5> ObtenerNivel5(int idTipoArbol, int idTipoUsuario, int idNivel4, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel5(idTipoArbol, idTipoUsuario, idNivel4, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel6> ObtenerNivel6(int idTipoArbol, int idTipoUsuario, int idNivel5, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel6(idTipoArbol, idTipoUsuario, idNivel5, insertarSeleccion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Arbol.Nodos.Nivel7> ObtenerNivel7(int idTipoArbol, int idTipoUsuario, int idNivel6, bool insertarSeleccion) {
            return base.Channel.ObtenerNivel7(idTipoArbol, idTipoUsuario, idNivel6, insertarSeleccion);
        }
        
        public bool EsNodoTerminal(int idTipoUsuario, int idTipoArbol, int nivel1, System.Nullable<int> nivel2, System.Nullable<int> nivel3, System.Nullable<int> nivel4, System.Nullable<int> nivel5, System.Nullable<int> nivel6, System.Nullable<int> nivel7) {
            return base.Channel.EsNodoTerminal(idTipoUsuario, idTipoArbol, nivel1, nivel2, nivel3, nivel4, nivel5, nivel6, nivel7);
        }
        
        public void GuardarArbol(KiiniNet.Entities.Cat.Operacion.ArbolAcceso arbol) {
            base.Channel.GuardarArbol(arbol);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Operacion.InformacionConsulta> ObtenerInformacionConsulta(KinniNet.Business.Utils.BusinessVariables.EnumTiposInformacionConsulta tipoinfoConsulta, bool insertarSeleccion) {
            return base.Channel.ObtenerInformacionConsulta(tipoinfoConsulta, insertarSeleccion);
        }
        
        public void GuardarInformacionConsulta(KiiniNet.Entities.Operacion.InformacionConsulta informacion) {
            base.Channel.GuardarInformacionConsulta(informacion);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.SLA> ObtenerSla(bool insertarSeleccion) {
            return base.Channel.ObtenerSla(insertarSeleccion);
        }
        
        public void GuardarSla(KiiniNet.Entities.Cat.Usuario.SLA sla) {
            base.Channel.GuardarSla(sla);
        }
        
        public System.Collections.Generic.List<KiiniNet.Entities.Cat.Usuario.Encuesta> ObtenerEncuestas(bool insertarSeleccion) {
            return base.Channel.ObtenerEncuestas(insertarSeleccion);
        }
        
        public void GuardarEncuesta(KiiniNet.Entities.Cat.Usuario.Encuesta encuesta) {
            base.Channel.GuardarEncuesta(encuesta);
        }
    }
}
